export const quotes = [
  "Keep moving forward!",
  "From failure, you learn. From success, not so much.",
  "Around here, however, we don't look backwards for very long.",
  "I never thought about stopping.",
  "You have failed. Excellent! It's just part of the process.",
  "Your future has not yet been written. No one's has. Your future is whatever you make it. So make it a good one.",
  "Failure is just another way to learn how to do it right.",
  "Don't let it get you down. It happens to the best of us.",
  "Look at that! It's beautiful! ...It failed! And it was awesome!",
  "If you want to maximize your success rates, you must double your failure rates.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The only real mistake is the one from which we learn nothing.",
  "Failure is the condiment that gives success its flavor.",
  "Believe you can and you're halfway there.",
  "The best way to predict the future is to create it.",
  "It is fine to celebrate success, but it is more important to heed the lessons of failure.",
  "Giving up is the only sure way to fail.",
  "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
  "Success consists of going from failure to failure without loss of enthusiasm.",
  "Mistakes are proof that you are trying.",
  "Fail fast, learn fast.",
  "Embrace the mess.",
  "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
  "Fall seven times, stand up eight.",
  "The master has failed more times than the beginner has even tried."
];
